name: MindsDB Pre-Releases

on:
  release:
    types:
      - prereleased

jobs:

  deploy_to_dockerhub:
      # Build our docker images based on our bake file
      runs-on: [self-hosted, dev]
      steps:
        - uses: actions/checkout@v2
        # Get clean environment variables via https://github.com/marketplace/actions/github-environment-variables-action
        - uses: FranzDiebold/github-env-vars-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Docker Login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push
          shell: bash
          run: |
            docker buildx create --name=remote-buildkit-agent --driver=remote --use tcp://remote-buildkit-agent.infrastructure.svc.cluster.local:80 || true # Create the builder (might already exist)
            VERSION=${{ env.CI_REF_NAME }} REGISTRY=mindsdb IMAGE=mindsdb-pre docker buildx bake --push --progress plain -f docker/docker-bake.hcl
